//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gorsel_proje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tblizinler
    {
        public int ID { get; set; }
        public Nullable<int> Personel { get; set; }
        public string BaslangicTarih { get; set; }
        public string BitisTarih { get; set; }
        public string Aciklama { get; set; }
    
        public virtual TblPersonel TblPersonel { get; set; }
    }
}
